namespace PgCompletionist;

public class SkillSet
{
    public Skill? Unknown { get; set; }
    public Skill? Unarmed { get; set; }
    public Skill? Mycology { get; set; }
    public Skill? Fishing { get; set; }
    public Skill? Lore { get; set; }
    public Skill? Sword { get; set; }
    public Skill? Mining { get; set; }
    public Skill? MushroomFarming { get; set; }
    public Skill? Dying { get; set; }
    public Skill? Gardening { get; set; }
    public Skill? Cooking { get; set; }
    public Skill? FireMagic { get; set; }
    public Skill? Gourmand { get; set; }
    public Skill? BeastSpeech { get; set; }
    public Skill? Anatomy { get; set; }
    public Skill? Pathology { get; set; }
    public Skill? ArtHistory { get; set; }
    public Skill? PoetryAppreciation { get; set; }
    public Skill? GenderStudies { get; set; }
    public Skill? Calligraphy { get; set; }
    public Skill? FirstAid { get; set; }
    public Skill? ArmorPatching { get; set; }
    public Skill? Carpentry { get; set; }
    public Skill? Psychology { get; set; }
    public Skill? Myconic { get; set; }
    public Skill? Foraging { get; set; }
    public Skill? Pig { get; set; }
    public Skill? Deer { get; set; }
    public Skill? Cow { get; set; }
    public Skill? Meditation { get; set; }
    public Skill? Alchemy { get; set; }
    public Skill? AnimalHandling { get; set; }
    public Skill? BattleChemistry { get; set; }
    public Skill? Staff { get; set; }
    public Skill? Necromancy { get; set; }
    public Skill? Skinning { get; set; }
    public Skill? Tanning { get; set; }
    public Skill? Mentalism { get; set; }
    public Skill? Anatomy_Elves { get; set; }
    public Skill? Anatomy_Rakshasa { get; set; }
    public Skill? Anatomy_Canines { get; set; }
    public Skill? Anatomy_Cats { get; set; }
    public Skill? Anatomy_Arthropods { get; set; }
    public Skill? Anatomy_Ruminants { get; set; }
    public Skill? Anatomy_Ungulates { get; set; }
    public Skill? Anatomy_Bears { get; set; }
    public Skill? Anatomy_Goblins { get; set; }
    public Skill? Anatomy_Fey { get; set; }
    public Skill? Anatomy_Orcs { get; set; }
    public Skill? Anatomy_Giants { get; set; }
    public Skill? Anatomy_Aberrations { get; set; }
    public Skill? Anatomy_Elementals { get; set; }
    public Skill? Anatomy_Constructs { get; set; }
    public Skill? Anatomy_Fish { get; set; }
    public Skill? Anatomy_Fungoids { get; set; }
    public Skill? Anatomy_Rodents { get; set; }
    public Skill? Anatomy_Demons { get; set; }
    public Skill? Anatomy_Dinosaurs { get; set; }
    public Skill? Anatomy_Humans { get; set; }
    public Skill? Anatomy_Undead { get; set; }
    public Skill? Anatomy_Incorporeal { get; set; }
    public Skill? Anatomy_Crones { get; set; }
    public Skill? Anatomy_Reptiles { get; set; }
    public Skill? Teleportation { get; set; }
    public Skill? Archery { get; set; }
    public Skill? Fletching { get; set; }
    public Skill? Leatherworking { get; set; }
    public Skill? SigilScripting { get; set; }
    public Skill? Spider { get; set; }
    public Skill? Endurance { get; set; }
    public Skill? Blacksmithing { get; set; }
    public Skill? Surveying { get; set; }
    public Skill? Geology { get; set; }
    public Skill? Notoriety { get; set; }
    public Skill? Goblinese { get; set; }
    public Skill? Cheesemaking { get; set; }
    public Skill? Textiles { get; set; }
    public Skill? Butchering { get; set; }
    public Skill? IocaineResistance { get; set; }
    public Skill? Tailoring { get; set; }
    public Skill? Shield { get; set; }
    public Skill? Oratory { get; set; }
    public Skill? Compassion { get; set; }
    public Skill? Phrenology { get; set; }
    public Skill? Phrenology_Humans { get; set; }
    public Skill? Phrenology_Elves { get; set; }
    public Skill? Phrenology_Rakshasa { get; set; }
    public Skill? Phrenology_Fae { get; set; }
    public Skill? Phrenology_Goblins { get; set; }
    public Skill? Phrenology_Orcs { get; set; }
    public Skill? Phrenology_Giants { get; set; }
    public Skill? Phrenology_Demons { get; set; }
    public Skill? Phrenology_Aberrations { get; set; }
    public Skill? Phrenology_Crones { get; set; }
    public Skill? DyeMaking { get; set; }
    public Skill? Hoplology { get; set; }
    public Skill? Hammer { get; set; }
    public Skill? Anatomy_Plants { get; set; }
    public Skill? Toolcrafting { get; set; }
    public Skill? Artistry { get; set; }
    public Skill? Vocabulary { get; set; }
    public Skill? Cartography { get; set; }
    public Skill? CorpseTalking { get; set; }
    public Skill? TreasureCartography { get; set; }
    public Skill? IceMagic { get; set; }
    public Skill? Performance { get; set; }
    public Skill? Performance_Strings { get; set; }
    public Skill? Performance_Percussion { get; set; }
    public Skill? Performance_Wind { get; set; }
    public Skill? ArmorAugmentBrewing { get; set; }
    public Skill? WeaponAugmentBrewing { get; set; }
    public Skill? AncillaryArmorAugmentBrewing { get; set; }
    public Skill? JewelryAugmentBrewing { get; set; }
    public Skill? CivicPride { get; set; }
    public Skill? Industry { get; set; }
    public Skill? Transmutation { get; set; }
    public Skill? GiantBat { get; set; }
    public Skill? BuckleArtistry { get; set; }
    public Skill? Autodidacticism { get; set; }
    public Skill? Gadgeteering { get; set; }
    public Skill? HolisticWellness { get; set; }
    public Skill? FlowerArrangement { get; set; }
    public Skill? NatureAppreciation { get; set; }
    public Skill? RetailManagement { get; set; }
    public Skill? Knife { get; set; }
    public Skill? SurvivalInstincts { get; set; }
    public Skill? Performance_Dance { get; set; }
    public Skill? ShamanicInfusion { get; set; }
    public Skill? IceConjuration { get; set; }
    public Skill? SushiPreparation { get; set; }
    public Skill? Crossbow { get; set; }
    public Skill? Orcish { get; set; }
    public Skill? Bard { get; set; }
    public Skill? Anatomy_Dwarves { get; set; }
    public Skill? Phrenology_Dwarves { get; set; }
    public Skill? Brewing { get; set; }
    public Skill? AlcoholTolerance { get; set; }
    public Skill? Rabbit { get; set; }
    public Skill? Priest { get; set; }
    public Skill? Gaming { get; set; }
    public Skill? Safecracking { get; set; }
    public Skill? JewelryCrafting { get; set; }
    public Skill? Warden { get; set; }
    public Skill? Genetics { get; set; }
    public Skill? Genetics_Arthropods { get; set; }
    public Skill? SpiritFox { get; set; }
    public Skill? CandleMaking { get; set; }
    public Skill? Golf { get; set; }
    public Skill? NonfictionWriting { get; set; }
    public Skill? AnimalHusbandry { get; set; }
    public Skill? Armorsmithing { get; set; }
    public Skill? Whittling { get; set; }
    public Skill? Paleontology { get; set; }
}
